setup ci cd

diff --git a/.github/workflows/gameplay-service.yaml b/.github/workflows/gameplay-service.yaml
--- a/.github/workflows/gameplay-service.yaml
+++ b/.github/workflows/gameplay-service.yaml
@@ -49,10 +49,19 @@ jobs:
   
     - name: Wait for Kaniko Build to Complete
       run: |
-        kubectl wait pod/gameplay-service-kaniko-build -n build \
-          --for=jsonpath="{.status.containerStatuses[0].state.terminated.reason}"=Completed \
-          --namespace build \
-          --timeout=20m
+        while true; do
+          STATUS=$(kubectl get pod gameplay-service-build-kaniko -n build -o jsonpath="{.status.containerStatuses[0].state.terminated.reason}")
+          if [ "$STATUS" == "Completed" ]; then
+            echo "Build Completed"
+            break
+          elif [ "$STATUS" == "Error" ]; then
+            echo "Build Failed"
+            exit 1
+          else
+            echo "Waiting for build to complete..."
+            sleep 10
+          fi
+        done
 
     - name: Set Environment Variables
       run: |
